version: '3.0'

services:
  main:
    container_name: main
    build: 
      context: .
    env_file:
      #- .development.env
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8001:8001
      - 9229:9229
    command: npm run start
    depends_on:
      - postgres
    restart: always
    networks:
      - bpt-main_default
  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      #- .development.env
      - .production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - bpt-main_default

networks:
  bpt-main_default:
    external: true

volumes:
  pgdata: